export const solarObjects = [
  {
    name: "Mercury",
    kind: "planet",
    visualRole: "planet",
    radius: 1.7,
    distance: 16,
    yearDays: 88,
    dayHours: 1407.6,
    tiltDeg: 0.03,
    texture: "./textures/2k_mercury.jpg",
    color: 0xb3a28a,
    hasOrbitRing: true,
    hasLabel: true,
  },
  {
    name: "Venus",
    kind: "planet",
    visualRole: "planet",
    radius: 2.5,
    distance: 22,
    yearDays: 224.7,
    dayHours: -5832.5,
    tiltDeg: 177.4,
    texture: "./textures/2k_venus_atmosphere.jpg",
    color: 0xd2a86b,
    hasOrbitRing: true,
    hasLabel: true,
  },
  {
    name: "Earth",
    kind: "planet",
    visualRole: "planet",
    radius: 2.65,
    distance: 30,
    yearDays: 365.25,
    dayHours: 23.93,
    tiltDeg: 23.44,
    texture: "./textures/land_ocean_ice_cloud_2048.jpg",
    color: 0x4f86ff,
    hasOrbitRing: true,
    hasLabel: true,
  },
  {
    name: "Mars",
    kind: "planet",
    visualRole: "planet",
    radius: 2.0,
    distance: 40,
    yearDays: 687,
    dayHours: 24.62,
    tiltDeg: 25.19,
    texture: "./textures/2k_mars.jpg",
    color: 0xc96f55,
    hasOrbitRing: true,
    hasLabel: true,
  },
  {
    name: "Asteroid Belt",
    kind: "belt",
    visualRole: "belt",
    innerRadius: 47,
    outerRadius: 58,
    thickness: 1.8,
    count: 900,
    yearDays: 1800,
    color: 0x8f8476,
    hasOrbitRing: false,
    hasLabel: false,
  },
  {
    name: "Ceres",
    kind: "dwarf",
    visualRole: "dwarf",
    radius: 0.75,
    distance: 52,
    yearDays: 1680,
    dayHours: 9.07,
    tiltDeg: 4,
    texture: "./textures/ceres.jpg",
    color: 0xb7b1a3,
    hasOrbitRing: true,
    hasLabel: true,
  },
  {
    name: "Jupiter",
    kind: "planet",
    visualRole: "planet",
    radius: 8.5,
    distance: 62,
    yearDays: 4331,
    dayHours: 9.93,
    tiltDeg: 3.13,
    texture: "./textures/2k_jupiter.jpg",
    color: 0xd2b28a,
    hasOrbitRing: true,
    hasLabel: true,
  },
  {
    name: "Saturn",
    kind: "planet",
    visualRole: "planet",
    radius: 7.2,
    distance: 88,
    yearDays: 10747,
    dayHours: 10.7,
    tiltDeg: 26.73,
    texture: "./textures/2k_saturn.jpg",
    color: 0xd9c58c,
    hasOrbitRing: true,
    hasLabel: true,
  },
  {
    name: "Saturn Ring",
    kind: "ring",
    visualRole: "ring",
    parentName: "Saturn",
    innerRadius: 7.2 * 1.3,
    outerRadius: 7.2 * 2.1,
    texture: "./textures/saturn_small_ring_tex.png",
    color: 0xffffff,
    hasOrbitRing: false,
    hasLabel: false,
  },
  {
    name: "Uranus",
    kind: "planet",
    visualRole: "planet",
    radius: 5.0,
    distance: 114,
    yearDays: 30589,
    dayHours: -17.24,
    tiltDeg: 97.77,
    texture: "./textures/2k_uranus.jpg",
    color: 0xa5d9e7,
    hasOrbitRing: true,
    hasLabel: true,
  },
  {
    name: "Neptune",
    kind: "planet",
    visualRole: "planet",
    radius: 4.9,
    distance: 140,
    yearDays: 59800,
    dayHours: 16.11,
    tiltDeg: 28.32,
    texture: "./textures/2k_neptune.jpg",
    color: 0x456ddd,
    hasOrbitRing: true,
    hasLabel: true,
  },
  {
    name: "Pluto",
    kind: "dwarf",
    visualRole: "dwarf",
    radius: 0.95,
    distance: 165,
    yearDays: 90560,
    dayHours: -153.3,
    tiltDeg: 119.6,
    texture: "./textures/2k_pluto.jpg",
    color: 0xbfae9c,
    hasOrbitRing: true,
    hasLabel: true,
  },
];
